GET http://localhost:8080/vhs

###

GET http://localhost:8080/vhs/VegieTales

###
POST http://localhost:8080/vhs HTTP/1.1
content-type: application/json

{
  "videoName": "Home Alone",
  "description": "A kid home alone for Christmas",
  "rating": "PG",
  "tapeCondition": "good",
  "price": 18.25,
  "content_warning": "none",
  "used": "true"
}

###

PUT http://localhost:8080/vhs/Home%20Alone HTTP/1.1
content-type: application/json

{
  "videoName": "Home Alone",
  "description": "A kid home alone for Christmas",
  "rating": "PG",
  "tapeCondition": "fair",
  "price": 10.25,
  "content_warning": "none",
  "used": "true"
}

###

DELETE http://localhost:8080/vhs/Home%20Alone

###

GET http://localhost:8080/books

###

GET http://localhost:8080/books/Fairy%20tales

###
POST http://localhost:8080/books HTTP/1.1
content-type: application/json

{
  "author": "Jane Pose",
  "country": "Atlantis",
  "imageLink": "images/PrideandFear.jpg",
  "language": "Greek",
  "link": "https://en.wikipedia.org/wiki/PrideandFear\n",
  "pages": 1300,
  "title": "PrideandFear",
  "year": 100
}

###

PUT http://localhost:8080/books/PrideandFear HTTP/1.1
content-type: application/json

{
  "author": "Jane Pose",
  "country": "Atlantis",
  "imageLink": "images/pride_and_fear.jpg",
  "language": "Spanish",
  "link": "https://en.wikipedia.org/wiki/PrideandFear\n",
  "pages": 1200,
  "title": "PrideandFear",
  "year": 100
}

###

DELETE http://localhost:8080/books/PrideandFear